
CREATE OR ALTER TASK {{environment}}.LOAD.TASK_EXCHANGE_RATE_REFRESH_DLY
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 09 * * * America/Los_Angeles'
  AS
    INSERT OVERWRITE INTO {{environment}}.LOAD.STG_EXCHANGE_RATE 
    select * from FINANCE__ECONOMICS.CYBERSYN.FX_RATES_TIMESERIES where QUOTE_CURRENCY_ID='INR' ORDER BY DATE DESC LIMIT 1;
